modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/SpaceXVI/Rough-Tweaks-Revamped/issues" #optional

[[mods]] #mandatory
modId="roughtweaks" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Rough Tweaks" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="logo.png" #optional
credits="Huge thanks to our lad, Lellson, for making this amazing mod and allowing me to ported it!" #optional
authors="MS55" #optional
description='''
Adds a bit of extra difficulty to the game
'''

[[dependencies.roughtweaks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.roughtweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
